# Generated by Django 3.2.4 on 2023-02-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'faq'},
        ),
    ]
