# Generated by Django 3.2.4 on 2023-02-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
