# Generated by Django 3.2.4 on 2023-02-06 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_in_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homepage_priority',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
