# Generated by Django 3.2.4 on 2023-02-09 05:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_homepage_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedTimeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('relative_discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(95)])),
                ('absolute_discount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'limited_time_offer',
                'verbose_name_plural': 'limited_time_offers',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='product',
            name='may_be_in_homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='limited_time_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.limitedtimeoffer'),
        ),
    ]
