# Generated by Django 3.2.4 on 2023-02-09 04:44

from django.db import migrations, models
import django.db.models.manager
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='dspskateshop'), upload_to='files/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
