# Generated by Django 3.2.4 on 2023-02-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='title',
            field=models.CharField(default='Patrocinado', max_length=64),
        ),
    ]
