# Generated by Django 3.2.4 on 2023-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='youtube',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
