# Generated by Django 3.2.4 on 2023-01-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20230110_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='youtube',
            field=models.CharField(max_length=70),
        ),
    ]
